import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#08111E",
  },
  screen: {
    flex: 1,
    backgroundColor: "#08111E",
  },
  centeredStage: {
    flex: 1,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  launchLogoWrap: {
    marginBottom: 26,
    padding: 18,
    borderRadius: 40,
    backgroundColor: "rgba(198,255,67,0.08)",
  },
  launchLogo: {
    width: 110,
    height: 110,
    borderRadius: 32,
    backgroundColor: "#C6FF43",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#C6FF43",
    shadowOpacity: 0.45,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 0 },
  },
  launchTitle: {
    color: "#C6FF43",
    fontSize: 38,
    fontWeight: "900",
    letterSpacing: 2,
    fontStyle: "italic",
  },
  launchTagline: {
    color: "#DDE5F2",
    fontSize: 18,
    textAlign: "center",
    lineHeight: 28,
    marginTop: 14,
    maxWidth: 280,
  },
  loginCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#131E2E",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(198,255,67,0.16)",
    padding: 22,
  },
  loginBadge: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "#C6FF43",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  loginTitle: {
    color: "#F4F7FB",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  loginSubtitle: {
    color: "#9EABC0",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  loginHint: {
    color: "#78869C",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 14,
  },
  loginError: {
    color: "#FF9AA5",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 12,
  },
  backgroundGlowTop: {
    position: "absolute",
    top: -80,
    left: -30,
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: "rgba(198,255,67,0.08)",
  },
  backgroundGlowBottom: {
    position: "absolute",
    bottom: 40,
    right: -60,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: "rgba(92,157,255,0.08)",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(198,255,67,0.18)",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  brandIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#C6FF43",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#C6FF43",
    shadowOpacity: 0.45,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
  },
  brandName: {
    color: "#B7F24A",
    fontSize: 26,
    fontWeight: "900",
    fontStyle: "italic",
    letterSpacing: 1.4,
  },
  brandSub: {
    color: "#7F8BA2",
    fontSize: 10,
    letterSpacing: 1.5,
    fontWeight: "700",
  },
  headerBadge: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(198,255,67,0.3)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0E1627",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 110,
  },
  contentStack: {
    gap: 18,
  },
  heroCard: {
    backgroundColor: "#111C2C",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(198,255,67,0.18)",
    padding: 22,
  },
  heroEyebrow: {
    color: "#BFC8D6",
    textAlign: "center",
    letterSpacing: 2.2,
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 16,
  },
  scoreFrame: {
    minHeight: 190,
    borderRadius: 28,
    borderWidth: 4,
    borderColor: "#B7F24A",
    backgroundColor: "#1A2431",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#B7F24A",
    shadowOpacity: 0.35,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 0 },
  },
  scoreValue: {
    color: "#C6FF43",
    fontSize: 62,
    fontWeight: "900",
  },
  scoreUnit: {
    color: "#E6ECF6",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1.8,
    marginTop: 6,
  },
  heroNote: {
    color: "#9AA8BC",
    fontSize: 14,
    lineHeight: 22,
    marginTop: 16,
  },
  dualCardRow: {
    gap: 18,
  },
  metricCard: {
    backgroundColor: "#1A2437",
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  metricCardAlt: {
    backgroundColor: "#223229",
    borderColor: "rgba(198,255,67,0.15)",
  },
  metricHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  metricLabel: {
    color: "#CED5E1",
    letterSpacing: 1.8,
    fontSize: 13,
    fontWeight: "800",
  },
  metricValue: {
    fontSize: 22,
    fontWeight: "900",
  },
  metricMuted: {
    color: "#B8C1CF",
    fontSize: 16,
    fontWeight: "700",
  },
  levelText: {
    color: "#C6FF43",
    fontSize: 22,
    fontWeight: "900",
  },
  metricHint: {
    color: "#A2AFC3",
    marginTop: 10,
    fontSize: 13,
  },
  progressTrack: {
    height: 18,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "#0B1322",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
  },
  aiCard: {
    backgroundColor: "#142131",
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(69,242,106,0.18)",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  sectionTitle: {
    color: "#E7EDF8",
    fontSize: 14,
    letterSpacing: 1.8,
    fontWeight: "900",
  },
  sectionValue: {
    color: "#C6FF43",
    fontSize: 18,
    fontWeight: "900",
  },
  aiBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#C6FF43",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  aiBadgeText: {
    color: "#08111E",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  aiTitle: {
    color: "#C6FF43",
    fontSize: 24,
    fontWeight: "900",
    marginTop: 8,
  },
  aiBody: {
    color: "#CDD6E4",
    lineHeight: 22,
    marginTop: 8,
    fontSize: 15,
  },
  storyCard: {
    backgroundColor: "#151D2A",
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(198,255,67,0.14)",
  },
  storyTrend: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.4,
  },
  storyTrendRecovery: {
    color: "#45F26A",
  },
  storyTrendWarning: {
    color: "#FF9AA5",
  },
  storyTrendSteady: {
    color: "#F8D866",
  },
  storyTitle: {
    color: "#F0F4FB",
    fontSize: 24,
    fontWeight: "900",
    marginTop: 6,
  },
  storyBody: {
    color: "#B9C5D8",
    lineHeight: 22,
    fontSize: 15,
    marginTop: 8,
  },
  storyTimeline: {
    marginTop: 18,
    minHeight: 118,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 10,
  },
  storyDayCard: {
    flex: 1,
    alignItems: "center",
    gap: 8,
  },
  storyDayLabel: {
    color: "#93A2B8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.1,
  },
  storyDayBar: {
    width: "100%",
    maxWidth: 28,
    borderRadius: 999,
  },
  storyDayValue: {
    color: "#EAF0F9",
    fontSize: 11,
    fontWeight: "800",
  },
  storyEmpty: {
    color: "#8E9AB0",
    fontSize: 14,
    lineHeight: 21,
    flex: 1,
  },
  questPanel: {
    backgroundColor: "#121C2B",
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    gap: 16,
  },
  questRow: {
    flexDirection: "row",
    gap: 14,
  },
  questIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 16,
    backgroundColor: "#202B3F",
    alignItems: "center",
    justifyContent: "center",
  },
  questMain: {
    flex: 1,
    gap: 6,
  },
  questTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  questTitle: {
    color: "#EFF4FD",
    fontSize: 17,
    fontWeight: "800",
    flex: 1,
    paddingRight: 10,
  },
  questXp: {
    color: "#45F26A",
    fontWeight: "900",
    fontSize: 15,
  },
  questDescription: {
    color: "#98A5B9",
    fontSize: 14,
    lineHeight: 21,
  },
  questProgressLabel: {
    color: "#DCE3F0",
    fontSize: 12,
    fontWeight: "700",
  },
  sectionCard: {
    backgroundColor: "#131E2E",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(198,255,67,0.15)",
    padding: 18,
  },
  sectionDescription: {
    color: "#A7B4C8",
    fontSize: 15,
    lineHeight: 23,
    marginTop: 10,
  },
  inputBlock: {
    marginTop: 16,
  },
  inputLabel: {
    color: "#D8E0ED",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#0B1322",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: "#F4F7FB",
    fontSize: 15,
  },
  moodRow: {
    flexDirection: "row",
    gap: 10,
  },
  moodChip: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: "#0B1322",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  moodChipActive: {
    backgroundColor: "#C6FF43",
    borderColor: "#C6FF43",
  },
  moodChipText: {
    color: "#DDE5F2",
    fontWeight: "800",
  },
  moodChipTextActive: {
    color: "#07111F",
  },
  primaryButton: {
    marginTop: 20,
    backgroundColor: "#C6FF43",
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  secondaryButton: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#121A29",
  },
  secondaryButtonText: {
    color: "#D9E1EE",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 1.3,
  },
  primaryButtonText: {
    color: "#08111E",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 1.3,
  },
  summaryCard: {
    backgroundColor: "#202834",
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  summaryText: {
    color: "#D1DAE7",
    lineHeight: 23,
    fontSize: 15,
  },
  summaryStrip: {
    gap: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#151F2F",
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  statLabel: {
    color: "#B9C4D5",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1.6,
    marginBottom: 10,
  },
  statValueRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  statValue: {
    fontSize: 42,
    fontWeight: "900",
  },
  statSuffix: {
    color: "#B6C0CE",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 6,
  },
  questDetailCard: {
    backgroundColor: "#1B2434",
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    gap: 10,
  },
  questDetailCardComplete: {
    borderColor: "rgba(69,242,106,0.28)",
  },
  questTrack: {
    height: 14,
  },
  questFooterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  questState: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.4,
  },
  profileCard: {
    backgroundColor: "#202A3A",
    borderRadius: 24,
    padding: 22,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(198,255,67,0.14)",
  },
  avatarShell: {
    width: 110,
    height: 110,
    borderRadius: 28,
    backgroundColor: "#C6FF43",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    shadowColor: "#C6FF43",
    shadowOpacity: 0.35,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 0 },
  },
  avatarLetter: {
    color: "#06111E",
    fontSize: 44,
    fontWeight: "900",
  },
  profileName: {
    color: "#F0F4FB",
    fontSize: 32,
    fontWeight: "900",
    textAlign: "center",
  },
  profileClass: {
    color: "#B7F24A",
    fontSize: 18,
    fontWeight: "700",
    marginTop: 6,
  },
  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(6,12,21,0.96)",
    borderTopWidth: 1,
    borderTopColor: "rgba(198,255,67,0.18)",
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 18,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 18,
  },
  tabItemActive: {
    backgroundColor: "rgba(198,255,67,0.08)",
    shadowColor: "#C6FF43",
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
  },
  tabLabel: {
    color: "#7C879E",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  tabLabelActive: {
    color: "#C6FF43",
  },
});
