create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text,
  hp integer not null default 100,
  xp integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  title text not null,
  distance_km numeric(6,2) not null check (distance_km >= 0),
  xp_earned integer not null default 0,
  completed_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  log_date date not null default current_date,
  sleep_hours numeric(4,1) not null check (sleep_hours >= 0),
  water_intake numeric(4,1) not null check (water_intake >= 0),
  mood integer not null check (mood between 1 and 5),
  activity text not null,
  activity_km numeric(6,2) not null default 0 check (activity_km >= 0),
  health_score integer not null check (health_score between 0 and 100),
  ai_advice text,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, log_date)
);

alter table public.daily_logs
add column if not exists ai_advice text;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.add_profile_xp(user_id uuid, xp_to_add integer)
returns setof public.profiles
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public.profiles
  set
    xp = xp + greatest(xp_to_add, 0),
    updated_at = timezone('utc', now())
  where id = user_id
  returning *;
end;
$$;

create or replace function public.add_profile_hp(user_id uuid, hp_to_add integer)
returns setof public.profiles
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public.profiles
  set
    hp = least(100, hp + greatest(hp_to_add, 0)),
    updated_at = timezone('utc', now())
  where id = user_id
  returning *;
end;
$$;

alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.daily_logs enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "activities_select_own" on public.activities;
create policy "activities_select_own"
on public.activities
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "activities_insert_own" on public.activities;
create policy "activities_insert_own"
on public.activities
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "daily_logs_select_own" on public.daily_logs;
create policy "daily_logs_select_own"
on public.daily_logs
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "daily_logs_insert_own" on public.daily_logs;
create policy "daily_logs_insert_own"
on public.daily_logs
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "daily_logs_update_own" on public.daily_logs;
create policy "daily_logs_update_own"
on public.daily_logs
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

grant execute on function public.add_profile_xp(uuid, integer) to authenticated;
grant execute on function public.add_profile_hp(uuid, integer) to authenticated;
